COPY instrument_calibration_values (instrument_id, mooring_id, datafile_pk, param_code, description, data_type, data_value) FROM stdin;
622	Pulse-7-2010             	100077	CH_ANALOG_DARK_COUNT                    	Dark counts for analog data	NUMBER    	0.072                                                                                                                   
622	Pulse-7-2010             	100077	CH_ANALOG_MAX_OUTPUT                    	Maximum output	NUMBER    	4.99                                                                                                                    
620	Pulse-7-2010             	100071	C3                                      	C3 coefficients	STRING    	-6.20004E-02,1.43629E-03,-2.90879E-05,2.67188E-07                                                                       
620	Pulse-7-2010             	100071	C4                                      	C4 coefficients	STRING    	2.39383E-04,-4.79250E-06,1.00060E-07,-9.33184E-10                                                                       
620	Pulse-6-2009             	100107	C3                                      	C3 coefficients	STRING    	-6.20004E-02,1.43629E-03,-2.90879E-05,2.67188E-07                                                                       
620	Pulse-7-2010             	100071	C1                                      	C1 coefficients	STRING    	-2.83515E+02,8.53926E+00,-1.70712E-01,1.51927E-03                                                                       
620	Pulse-7-2010             	100071	C2                                      	C2 coefficients	STRING    	6.14613E+00,-1.62949E-01,3.25579E-03,-2.94146E-05                                                                       
621	Pulse-7-2010             	100075	SOC                                     	Soc coefficient	NUMBER    	0.4873                                                                                                                  
621	Pulse-7-2010             	100075	V_OFFSET                                	V offset value	NUMBER    	-0.4886                                                                                                                 
621	Pulse-7-2010             	100075	TAU_20                                  	Tau 20 value	NUMBER    	5.56                                                                                                                    
621	Pulse-7-2010             	100075	A_COEFF                                 	A coefficient	NUMBER    	-2.4093E-003                                                                                                            
621	Pulse-7-2010             	100075	B_COEFF                                 	B coefficient	NUMBER    	1.1208E-004                                                                                                             
621	Pulse-7-2010             	100075	C_COEFF                                 	C coefficient	NUMBER    	-2.4562E-006                                                                                                            
621	Pulse-7-2010             	100075	E_NOMINAL                               	E nominal value	NUMBER    	0.036                                                                                                                   
621	Pulse-7-2010             	100075	D1_COEFF                                	D1 coefficient	NUMBER    	1.92634E-4                                                                                                              
621	Pulse-7-2010             	100075	D2_COEFF                                	d2 coefficient	NUMBER    	-4.64803E-3                                                                                                             
621	Pulse-7-2010             	100075	H1_COEFF                                	H1 coefficient	NUMBER    	-3.30000E-2                                                                                                             
621	Pulse-7-2010             	100075	H2_COEFF                                	H2 coefficient	NUMBER    	5.00000E+3                                                                                                              
621	Pulse-7-2010             	100075	H3_COEFF                                	H3 coefficient	NUMBER    	1.45000E+3                                                                                                              
620	Pulse-7-2010             	100071	C0                                      	C0 coefficients	STRING    	5.27602E+03,-1.78336E+02,3.60337E+00,-3.17257E-02                                                                       
620	Pulse-6-2009             	100107	C4                                      	C4 coefficients	STRING    	2.39383E-04,-4.79250E-06,1.00060E-07,-9.33184E-10                                                                       
620	Pulse-6-2009             	100107	C1                                      	C1 coefficients	STRING    	-2.83515E+02,8.53926E+00,-1.70712E-01,1.51927E-03                                                                       
620	Pulse-6-2009             	100107	C2                                      	C2 coefficients	STRING    	6.14613E+00,-1.62949E-01,3.25579E-03,-2.94146E-05                                                                       
622	Pulse-7-2010             	100077	CH_ANALOG_RESOLUTION                    	Resolution	NUMBER    	1.8                                                                                                                     
622	Pulse-7-2010             	100077	CH_ANALOG_SCALE_FACTOR                  	Scale Factor (SF)	NUMBER    	10                                                                                                                      
622	Pulse-7-2010             	100077	TURB_ANALOG_DARK_COUNT                  	Turbidity dark count - analog	NUMBER    	0.060                                                                                                                   
622	Pulse-7-2010             	100077	TURB_ANALOG_NTU_VALUE                   	NTU solution value - analog	NUMBER    	2.51                                                                                                                    
622	Pulse-7-2010             	100077	TURB_ANALOG_MAX_OUTPUT                  	Maximum output - analog	NUMBER    	4.98                                                                                                                    
622	Pulse-7-2010             	100077	TURB_ANALOG_RESOLUTION                  	Resolution - analog	NUMBER    	1.8                                                                                                                     
622	Pulse-7-2010             	100077	CH_DIGITAL_DARK_COUNT                   	Dark count - digital	NUMBER    	54                                                                                                                      
622	Pulse-7-2010             	100077	CH_DIGITAL_SCALE_FACTOR                 	Scale factor - digital	NUMBER    	0.0121                                                                                                                  
622	Pulse-7-2010             	100077	CH_DIGITAL_MAX_OUTPUT                   	Max output - digital	NUMBER    	4117                                                                                                                    
622	Pulse-7-2010             	100077	CH_DIGITAL_RESOLUTION                   	Resolution - digital	NUMBER    	1.9                                                                                                                     
622	Pulse-7-2010             	100077	TURB_DIGITAL_DARK_COUNT                 	Dark count - digital	NUMBER    	47                                                                                                                      
622	Pulse-7-2010             	100077	TURB_DIGITAL_NTU_VALUE                  	NTU solution value - digital	NUMBER    	2056                                                                                                                    
622	Pulse-7-2010             	100077	TURB_DIGITAL_MAX_OUTPUT                 	Maximum output - digital	NUMBER    	4117                                                                                                                    
622	Pulse-7-2010             	100077	TURB_DIGITAL_RESOLUTION                 	Resolution - digital	NUMBER    	1.7                                                                                                                     
622	Pulse-7-2010             	100077	TURB_DIGITAL_SCALE_FACTOR               	Scale factor - digital	NUMBER    	0.0057                                                                                                                  
622	Pulse-7-2010             	100077	TURB_ANALOG_SCALE_FACTOR                	scale factor - analog	NUMBER    	5.00                                                                                                                    
619	Pulse-7-2010             	100079	SERIAL_NUMBER                           	Device serial number	STRING    	PARS-135                                                                                                                
619	Pulse-7-2010             	100079	CALIBRATION_DATE                        	Date of calibration	DATE      	27032009                                                                                                                
619	Pulse-7-2010             	100079	IM_ANALOG_COEFFICIENT                   	Im coefficient - analog	NUMBER    	1.3589                                                                                                                  
619	Pulse-7-2010             	100079	IM_DIGITAL_COEFFICIENT                  	Im coefficient - digital	NUMBER    	1.3589                                                                                                                  
619	Pulse-7-2010             	100079	A1_ANALOG_COEFFICIENT                   	A1 coefficient - analog	NUMBER    	0.8946                                                                                                                  
619	Pulse-7-2010             	100079	A1_DIGITAL_COEFFICIENT                  	A1 coefficient - digital	NUMBER    	2943.4639                                                                                                               
619	Pulse-7-2010             	100079	A0_ANALOG_COEFFICIENT                   	A0 coefficient - analog	NUMBER    	1.3285                                                                                                                  
619	Pulse-7-2010             	100079	A0_DIGITAL_COEFFICIENT                  	A0 coefficient - digital	NUMBER    	4374.0529                                                                                                               
621	Pulse-6-2009             	100209	SOC                                     	Soc coefficient	NUMBER    	0.4873                                                                                                                  
621	Pulse-6-2009             	100209	V_OFFSET                                	V offset value	NUMBER    	-0.4886                                                                                                                 
621	Pulse-6-2009             	100209	TAU_20                                  	Tau 20 value	NUMBER    	5.56                                                                                                                    
621	Pulse-6-2009             	100209	A_COEFF                                 	A coefficient	NUMBER    	-2.4093E-003                                                                                                            
621	Pulse-6-2009             	100209	B_COEFF                                 	B coefficient	NUMBER    	1.1208E-004                                                                                                             
621	Pulse-6-2009             	100209	C_COEFF                                 	C coefficient	NUMBER    	-2.4562E-006                                                                                                            
621	Pulse-6-2009             	100209	E_NOMINAL                               	E nominal value	NUMBER    	0.036                                                                                                                   
621	Pulse-6-2009             	100209	D1_COEFF                                	D1 coefficient	NUMBER    	1.92634E-4                                                                                                              
621	Pulse-6-2009             	100209	D2_COEFF                                	d2 coefficient	NUMBER    	-4.64803E-3                                                                                                             
621	Pulse-6-2009             	100209	H1_COEFF                                	H1 coefficient	NUMBER    	-3.30000E-2                                                                                                             
621	Pulse-6-2009             	100209	H2_COEFF                                	H2 coefficient	NUMBER    	5.00000E+3                                                                                                              
621	Pulse-6-2009             	100209	H3_COEFF                                	H3 coefficient	NUMBER    	1.45000E+3                                                                                                              
620	Pulse-6-2009             	100107	C0                                      	C0 coefficients	STRING    	5.27602E+03,-1.78336E+02,3.60337E+00,-3.17257E-02                                                                       
619	Pulse-6-2009             	100079	A0_ANALOG_COEFFICIENT                   	A0 coefficient - analog	NUMBER    	1.3285                                                                                                                  
619	Pulse-6-2009             	100079	A0_DIGITAL_COEFFICIENT                  	A0 coefficient - digital	NUMBER    	4374.0529                                                                                                               
619	Pulse-6-2009             	100079	A1_ANALOG_COEFFICIENT                   	A1 coefficient - analog	NUMBER    	0.8946                                                                                                                  
619	Pulse-6-2009             	100079	A1_DIGITAL_COEFFICIENT                  	A1 coefficient - digital	NUMBER    	2943.4639                                                                                                               
619	Pulse-6-2009             	100079	CALIBRATION_DATE                        	Date of calibration	DATE      	27032009                                                                                                                
619	Pulse-6-2009             	100079	IM_ANALOG_COEFFICIENT                   	Im coefficient - analog	NUMBER    	1.3589                                                                                                                  
619	Pulse-6-2009             	100079	IM_DIGITAL_COEFFICIENT                  	Im coefficient - digital	NUMBER    	1.3589                                                                                                                  
619	Pulse-6-2009             	100079	SERIAL_NUMBER                           	Device serial number	STRING    	PARS-135                                                                                                                
622	Pulse-6-2009             	100077	CH_ANALOG_DARK_COUNT                    	Dark counts for analog data	NUMBER    	0.072                                                                                                                   
622	Pulse-6-2009             	100077	CH_ANALOG_MAX_OUTPUT                    	Maximum output	NUMBER    	4.99                                                                                                                    
622	Pulse-6-2009             	100077	CH_ANALOG_RESOLUTION                    	Resolution	NUMBER    	1.8                                                                                                                     
622	Pulse-6-2009             	100077	CH_ANALOG_SCALE_FACTOR                  	Scale Factor (SF)	NUMBER    	10                                                                                                                      
622	Pulse-6-2009             	100077	CH_DIGITAL_DARK_COUNT                   	Dark count - digital	NUMBER    	54                                                                                                                      
622	Pulse-6-2009             	100077	CH_DIGITAL_MAX_OUTPUT                   	Max output - digital	NUMBER    	4117                                                                                                                    
622	Pulse-6-2009             	100077	CH_DIGITAL_RESOLUTION                   	Resolution - digital	NUMBER    	1.9                                                                                                                     
622	Pulse-6-2009             	100077	CH_DIGITAL_SCALE_FACTOR                 	Scale factor - digital	NUMBER    	0.0121                                                                                                                  
622	Pulse-6-2009             	100077	TURB_ANALOG_DARK_COUNT                  	Turbidity dark count - analog	NUMBER    	0.060                                                                                                                   
622	Pulse-6-2009             	100077	TURB_ANALOG_MAX_OUTPUT                  	Maximum output - analog	NUMBER    	4.98                                                                                                                    
622	Pulse-6-2009             	100077	TURB_ANALOG_NTU_VALUE                   	NTU solution value - analog	NUMBER    	2.51                                                                                                                    
622	Pulse-6-2009             	100077	TURB_ANALOG_RESOLUTION                  	Resolution - analog	NUMBER    	1.8                                                                                                                     
622	Pulse-6-2009             	100077	TURB_ANALOG_SCALE_FACTOR                	scale factor - analog	NUMBER    	5.00                                                                                                                    
622	Pulse-6-2009             	100077	TURB_DIGITAL_DARK_COUNT                 	Dark count - digital	NUMBER    	47                                                                                                                      
622	Pulse-6-2009             	100077	TURB_DIGITAL_MAX_OUTPUT                 	Maximum output - digital	NUMBER    	4117                                                                                                                    
622	Pulse-6-2009             	100077	TURB_DIGITAL_NTU_VALUE                  	NTU solution value - digital	NUMBER    	2056                                                                                                                    
622	Pulse-6-2009             	100077	TURB_DIGITAL_RESOLUTION                 	Resolution - digital	NUMBER    	1.7                                                                                                                     
622	Pulse-6-2009             	100077	TURB_DIGITAL_SCALE_FACTOR               	Scale factor - digital	NUMBER    	0.0057                                                                                                                  
\.