/*
 * IMOS data delivery project
 * Written by Peter Wiley
 * This code is copyright (c) Peter Wiley 2000 - ?
 * It is made available under the BSD Software Licence in the hope that it may be useful.
 * It has NO WARRANTY OF FITNESS OR SUITABILITY FOR ANY PURPOSE.
 * Feel free to fix any bugs that you may find.
 */

/*
 * InstrumentCalibrationFileForm.java
 *
 * Created on Mar 1, 2012, 9:48:27 PM
 */

package org.imos.dwm.forms;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Properties;
import java.util.TimeZone;
import java.util.logging.Level;
import javax.swing.JFrame;
import org.apache.log4j.Logger;
import org.imos.dwm.dbms.Instrument;
import org.imos.dwm.dbms.InstrumentCalibrationFile;
import org.wiley.core.Common;
import org.wiley.core.forms.MemoryWindow;

/**
 *
 * @author peter
 */
public class InstrumentCalibrationFileForm extends MemoryWindow
{

    private boolean isDataEditable = true;
    private JFrame parentFrame = null;
    private static Logger logger = Logger.getLogger(InstrumentCalibrationFileForm.class.getName());

    private Instrument parentInstrument = null;
    private InstrumentCalibrationFile editableItem = null;
    private InstrumentCalibrationFile savedItem = null;

    private boolean insertMode          = true;
    private boolean updateMode          = false;

    boolean isUpdateMode = false;
    
    File optionsFile = null;

    /** Creates new form InstrumentCalibrationFileForm */
    public InstrumentCalibrationFileForm()
    {
        initComponents();
        TimeZone.setDefault(TimeZone.getTimeZone("GMT"));
        BufferedReader br = null;
        String $HOME = System.getProperty("user.home");

        optionsFile = new File("ABOS.properties");
        
        try
        {
            Properties p = new Properties();
            br = new BufferedReader(new FileReader(optionsFile));
            p.load(br);
            dataFileField.setDefaultDirectory(p.getProperty("calfile-dir"));
        }
        catch (FileNotFoundException ex)
        {
            logger.warn(ex);
        }
        catch (IOException ex)
        {
            logger.warn(ex);
        }
        finally
        {
            try
            {
                br.close();
            }
            catch (IOException ex)
            {
                logger.warn(ex);
            }
        }
        
    }

    public void clearForm()
    {
        dataFileField.setFileName("");
    }

    public void setDataEditable(boolean b)
    {
        isDataEditable = b;
    }

    public void setParent(Frame parent)
    {
        parentFrame = (JFrame) parent;
    }

    public void setInstrument(Instrument ins)
    {
        parentInstrument = ins;
        instrumentIDPanel.setInstrument(ins);
    }

    public void setNew()
    {
        editableItem = new InstrumentCalibrationFile();
        savedItem = new InstrumentCalibrationFile();

        updateMode = false;
        insertMode = true;
    }

    public void setNew(InstrumentCalibrationFile newRow)
    {
        editableItem = newRow;
        savedItem = new InstrumentCalibrationFile();

        updateMode = false;
        insertMode = true;
    }

    public void setInstrumentCalibrationFile(InstrumentCalibrationFile f)
    {
        savedItem = f;
        try
        {
            editableItem = (InstrumentCalibrationFile)f.clone();
        }
        catch( CloneNotSupportedException cne )
        {
            logger.error( "attempt to clone object failed.");
            return;
        }

        instrumentIDPanel.setInstrument(parentInstrument);
        dataFileField.setFileName(savedItem.getFilePath());

        updateMode = true;
        insertMode = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instrumentIDPanel = new org.imos.dwm.dbms.fields.InstrumentIDPanel();
        dataFileField = new org.wiley.util.FileSelectorField();
        buttonPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        saveButton.setMnemonic('s');
        saveButton.setText("Save");
        saveButton.setPreferredSize(new java.awt.Dimension(70, 29));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setMnemonic('u');
        cancelButton.setText("Undo");
        cancelButton.setPreferredSize(new java.awt.Dimension(70, 29));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        quitButton.setMnemonic('q');
        quitButton.setText("Quit");
        quitButton.setMaximumSize(new java.awt.Dimension(80, 29));
        quitButton.setPreferredSize(new java.awt.Dimension(70, 29));
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout buttonPanelLayout = new org.jdesktop.layout.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(saveButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(110, 110, 110)
                .add(quitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(71, 71, 71))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(buttonPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(quitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(saveButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(dataFileField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(instrumentIDPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(buttonPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(instrumentIDPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(dataFileField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(buttonPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        boolean OK = false;

        if ( insertMode )
        {
            editableItem.setDataFilePrimaryKey(InstrumentCalibrationFile.getNextSequenceNumber());
            editableItem.setInstrumentID(parentInstrument.getInstrumentID()) ;
            editableItem.setSelectedFile(dataFileField.getSelectedFile());

            OK = editableItem.insert();
            try
            {
                Common.getConnection().commit();
            }
            catch (SQLException ex)
            {
                java.util.logging.Logger.getLogger(InstrumentCalibrationFileForm.class.getName()).log(Level.SEVERE, null, ex);
            }

            if ( OK )
            {
                savedItem = editableItem;
                quitButtonActionPerformed( new ActionEvent(this, 0, "SUCCESS") );
            }
            else
            {
                Common.showMessage("SQL Error on Insert", editableItem.getLastErrorMessage());
            }
        }
        else if ( updateMode )
        {
            editableItem.setInstrumentID(parentInstrument.getInstrumentID()) ;
            editableItem.setSelectedFile(dataFileField.getSelectedFile());

            OK = editableItem.update();
            if ( OK )
            {
                quitButtonActionPerformed( new ActionEvent(this, 0, "SUCCESS") );
            }
            else
            {
                Common.showMessage("SQL Error on Update", editableItem.getLastErrorMessage());
            }
        }
        
        if ( OK )
        {
            BufferedReader br = null;
            try
            {
                Properties p = new Properties();
                br = new BufferedReader(new FileReader(optionsFile));
                p.load(br);
                p.setProperty("calfile-dir", "" + dataFileField.getSelectedFile().getParent());
                BufferedWriter bw = new BufferedWriter(new FileWriter(optionsFile));
                p.store(bw, "ABOS user config");
            }
            catch (FileNotFoundException ex)
            {
                logger.warn(ex);
            }
            catch (IOException ex)
            {
                logger.warn(ex);
            }
            finally
            {
                try
                {
                    br.close();
                }
                catch (IOException ex)
                {
                    logger.warn(ex);
                }
            }
        }
}//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if( updateMode)
        {
            instrumentIDPanel.setInstrument(parentInstrument);
            dataFileField.setFileName(savedItem.getFilePath());
        }
        else
        {
            clearForm();
        }
}//GEN-LAST:event_cancelButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        if( !(evt.getActionCommand().equalsIgnoreCase("SUCCESS")) ) {
            // failed insert/update and user is quitting
            if (insertMode)
                savedItem = null;
            else if (updateMode)
                cancelButtonActionPerformed( null );
        }

        this.setVisible( false );
}//GEN-LAST:event_quitButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstrumentCalibrationFileForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private org.wiley.util.FileSelectorField dataFileField;
    private org.imos.dwm.dbms.fields.InstrumentIDPanel instrumentIDPanel;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

}
