COPY instrument_calibration_values (instrument_id, mooring_id, datafile_pk, param_code, description, data_type, data_value) FROM stdin;
742	Pulse-8-2011        	100228	A_COEFF                                 	A coefficient	NUMBER    	-2.579E-003                                                                                                             
742	Pulse-8-2011        	100228	B_COEFF                                 	B coefficient	NUMBER    	1.6628E-004                                                                                                             
742	Pulse-8-2011        	100228	C_COEFF                                 	C coefficient	NUMBER    	-3.1959E-006                                                                                                            
742	Pulse-8-2011        	100228	D1_COEFF                                	D1 coefficient	NUMBER    	1.92634E-4                                                                                                              
742	Pulse-8-2011        	100228	D2_COEFF                                	D2 coefficient	NUMBER    	-4.64803E-3                                                                                                             
742	Pulse-8-2011        	100228	E_NOMINAL                               	E nominal value	NUMBER    	0.036                                                                                                                   
742	Pulse-8-2011        	100228	H1_COEFF                                	H1 coefficient	NUMBER    	-3.30000E-2                                                                                                             
742	Pulse-8-2011        	100228	H2_COEFF                                	H2 coefficient	NUMBER    	5.00000E+3                                                                                                              
742	Pulse-8-2011        	100228	H3_COEFF                                	H3 coefficient	NUMBER    	1.45000E+3                                                                                                              
742	Pulse-8-2011        	100228	REPORT                                  	Calibration Report	STRING    	CSIRO CMAR-Hobart 27-Jul-2011 916DO                                                                                     
742	Pulse-8-2011        	100228	SOC                                     	Soc coefficient	NUMBER    	0.45523758                                                                                                              
742	Pulse-8-2011        	100228	TAU_20                                  	Tau 20 value	NUMBER    	5.56                                                                                                                    
742	Pulse-8-2011        	100228	V_OFFSET                                	V offset value	NUMBER    	-0.404528                                                                                                               
\.